parameters:
#    vamsii_site.example.class: Vamsii\SiteBundle\Example

services:
#    vamsii_site.example:
#        class: %vamsii_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
